server:
  servlet:
    context-path: /api
  port: 8081

spring:
  banner:
    charset: UTF-8

  data:
    mongodb:
      uri: mongodb+srv://admin:A3zm5byaTvBiXm3@cluster0.koqbg.mongodb.net/ladys_db?retryWrites=true&w=majority

  jpa:
    hibernate:
      ddl-auto: none

  elasticsearch:
    rest:
      read-timeout: 60

springdoc:
  swagger-ui:
    path: /
