spring:
  datasource:
    url: jdbc:postgresql://ec2-3-215-207-12.compute-1.amazonaws.com:5432/d7brpqckv79ojq
    username: qcfqkuberdikpu
    password: 8f380c7c35289f6d66a9b814de7de116443211cfccfb4bbe5fd9a62c104ecf6e
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
