spring:
  datasource:
    url: jdbc:postgresql://ec2-54-161-58-21.compute-1.amazonaws.com:5432/dbeer4kir2uqc0
    username: wwvzxbtwlxxjqf
    password: d7392d1a9067173e32aa3307cc30a99280bcf6bce442c05e5b6662992730147b
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
