spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/area-codes
    username: postgres
    password: 58326248
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
