server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  application:
    name: user_api
  messages:
    basename: error-messages
    encoding: UTF-8
  mvc:
    locale: en_US

  banner:
    charset: UTF-8

jwt:
  secret: TGFkeSdzIFNwYWNlIEpTT04gV2ViIFRva2VuIFNlY3JldCBLZXk=
  expiration: 24
