server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  banner:
    charset: UTF-8
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: TGFkeSdzIFNwYWNlIEpTT04gV2ViIFRva2VuIFNlY3JldCBLZXk=
  expiration: 24
