spring:
  datasource:
    url: jdbc:postgresql://ec2-52-5-176-53.compute-1.amazonaws.com:5432/d29abvhrgkbqmh
    username: nkbwgnmuwwpime
    password: aa38604334390ba564c06b39f9f4240b1e55aeb8a22920ce0e5a0134f7bc6720
    driver-class-name: org.postgresql.Driver

    tomcat:
      max-active: 4

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
