spring:
  datasource:
    url: jdbc:postgresql://ec2-100-25-100-81.compute-1.amazonaws.com:5432/d6ufi5d7n516va
    username: ypdnbuogzgsvlv
    password: 57cfd8414884aa69dfdf14ac3c2fcbb2302acb64518a0b5b7f97bb574879301f
    driver-class-name: org.postgresql.Driver

    tomcat:
      max-active: 4

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
